name: production-release

on:
  release:
    types: [published]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      # This merges main to production to trigger a vercel deploy
      - name: Merge main -> production
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          head_to_merge: ${{ github.ref }}
          target_branch: production
          github_token: ${{ github.token }}
